name: Vcflib CI
on: [push, pull_request]
jobs:
  arch:
    name: vcflib-CI
    runs-on: ubuntu-latest

    strategy:
      matrix:
        os: [ubuntu-latest]
        python-version: [3.8]
    steps:
    - name: apt update
      run: sudo apt-get -o Acquire::Retries=3 update
    - name: install dependencies
      run: sudo apt-get -o Acquire::Retries=3 install -y -V
        cmake
        libhts-dev
        libtabixpp-dev
        libtabixpp0
        libcurl4-openssl-dev
        pybind11-dev
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v1
      with:
        python-version: ${{ matrix.python-version }}
    - name: Checkout submodules
      run: git submodule update --init --recursive
    - name: Configure
      run: |
        mkdir -p build
        cd build
        cmake ..
    - name: Compile
      run: cmake --build build/ --verbose -- -j 2
    - name: Run tests
      run: |
        cd build
        ctest --verbose
